# Site settings
author: Dominic
title: Title
header-img: img/home-bg.png
email: dominicbarajas548@gmail.com
copyright_name: Dominic
description: > # this means to ignore newlines until "baseurl:"
  learning a new skill
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Santiago548

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
